/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as MatchesRouteImport } from "./routes/matches"
import { Route as GuideRouteImport } from "./routes/guide"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SeriesIndexRouteImport } from "./routes/series/index"
import { Route as SeriesIdRouteImport } from "./routes/series/$id"

const MatchesRoute = MatchesRouteImport.update({
    id: "/matches",
    path: "/matches",
    getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
    id: "/guide",
    path: "/guide",
    getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
    id: "/about",
    path: "/about",
    getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
    id: "/series/",
    path: "/series/",
    getParentRoute: () => rootRouteImport,
} as any)
const SeriesIdRoute = SeriesIdRouteImport.update({
    id: "/series/$id",
    path: "/series/$id",
    getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute
    "/about": typeof AboutRoute
    "/guide": typeof GuideRoute
    "/matches": typeof MatchesRoute
    "/series/$id": typeof SeriesIdRoute
    "/series/": typeof SeriesIndexRoute
}
export interface FileRoutesByTo {
    "/": typeof IndexRoute
    "/about": typeof AboutRoute
    "/guide": typeof GuideRoute
    "/matches": typeof MatchesRoute
    "/series/$id": typeof SeriesIdRoute
    "/series": typeof SeriesIndexRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    "/": typeof IndexRoute
    "/about": typeof AboutRoute
    "/guide": typeof GuideRoute
    "/matches": typeof MatchesRoute
    "/series/$id": typeof SeriesIdRoute
    "/series/": typeof SeriesIndexRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths: "/" | "/about" | "/guide" | "/matches" | "/series/$id" | "/series/"
    fileRoutesByTo: FileRoutesByTo
    to: "/" | "/about" | "/guide" | "/matches" | "/series/$id" | "/series"
    id: "__root__" | "/" | "/about" | "/guide" | "/matches" | "/series/$id" | "/series/"
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute
    AboutRoute: typeof AboutRoute
    GuideRoute: typeof GuideRoute
    MatchesRoute: typeof MatchesRoute
    SeriesIdRoute: typeof SeriesIdRoute
    SeriesIndexRoute: typeof SeriesIndexRoute
}

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/matches": {
            id: "/matches"
            path: "/matches"
            fullPath: "/matches"
            preLoaderRoute: typeof MatchesRouteImport
            parentRoute: typeof rootRouteImport
        }
        "/guide": {
            id: "/guide"
            path: "/guide"
            fullPath: "/guide"
            preLoaderRoute: typeof GuideRouteImport
            parentRoute: typeof rootRouteImport
        }
        "/about": {
            id: "/about"
            path: "/about"
            fullPath: "/about"
            preLoaderRoute: typeof AboutRouteImport
            parentRoute: typeof rootRouteImport
        }
        "/": {
            id: "/"
            path: "/"
            fullPath: "/"
            preLoaderRoute: typeof IndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        "/series/": {
            id: "/series/"
            path: "/series"
            fullPath: "/series/"
            preLoaderRoute: typeof SeriesIndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        "/series/$id": {
            id: "/series/$id"
            path: "/series/$id"
            fullPath: "/series/$id"
            preLoaderRoute: typeof SeriesIdRouteImport
            parentRoute: typeof rootRouteImport
        }
    }
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    AboutRoute: AboutRoute,
    GuideRoute: GuideRoute,
    MatchesRoute: MatchesRoute,
    SeriesIdRoute: SeriesIdRoute,
    SeriesIndexRoute: SeriesIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
